services:
  - type: web
    name: iste-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production 